services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template:ro
    environment:
      - SWAGGER_SERVICE_PORT=${SWAGGER_SERVICE_PORT}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
      - CUSTOMER_SERVICE_PORT=${CUSTOMER_SERVICE_PORT}
      - SALES_SERVICE_PORT=${SALES_SERVICE_PORT}
      - NGINX_PORT=${NGINX_PORT}
    command: /bin/sh -c "envsubst '$$AUTH_SERVICE_PORT $$CUSTOMER_SERVICE_PORT $$SALES_SERVICE_PORT $$SWAGGER_SERVICE_PORT $$NGINX_PORT' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - auth-service
      - customer-service
      - sales-service

  swagger-service:
    build: ./services/swagger-service
    container_name: swagger-service
    environment:
      - PORT=${SWAGGER_SERVICE_PORT}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
      - CUSTOMER_SERVICE_PORT=${CUSTOMER_SERVICE_PORT}
      - SALES_SERVICE_PORT=${SALES_SERVICE_PORT}

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    depends_on:
      - mongodb_auth_service
    environment:
      - PROJECT_NAME="Auth Service for Mindset Institute Microservices Project"
      - PORT=${AUTH_SERVICE_PORT}
      - JWT_EXPIRES=${JWT_EXPIRATION_TIME}
      - JWT_SECRET=${JWT_SECRET_KEY}
      - DB_URI=mongodb://${MONGODB_AUTH_SERVICE_USERNAME}:${MONGODB_AUTH_SERVICE_PASSWORD}@mongodb_auth_service:${MONGODB_AUTH_SERVICE_INTERNAL_PORT}/${MONGODB_AUTH_SERVICE_DATABASE}?authSource=admin

  customer-service:
    build: ./services/customer-service
    container_name: customer-service
    depends_on:
      - mongodb_customer_service
    environment:
      - PROJECT_NAME="Customer Service for Mindset Institute Microservices Project"
      - PORT=${CUSTOMER_SERVICE_PORT}
      - DB_URI=mongodb://${MONGODB_CUSTOMER_SERVICE_USERNAME}:${MONGODB_CUSTOMER_SERVICE_PASSWORD}@mongodb_customer_service:${MONGODB_CUSTOMER_SERVICE_INTERNAL_PORT}/${MONGODB_CUSTOMER_SERVICE_DATABASE}?authSource=admin

  sales-service:
    build: ./services/sales-service
    container_name: sales-service
    depends_on:
      - mongodb_sales_service
    environment:
      - PROJECT_NAME="Sales Service for Mindset Institute Microservices Project"
      - PORT=${SALES_SERVICE_PORT}
      - DB_URI=mongodb://${MONGODB_SALES_SERVICE_USERNAME}:${MONGODB_SALES_SERVICE_PASSWORD}@mongodb_sales_service:${MONGODB_SALES_SERVICE_INTERNAL_PORT}/${MONGODB_SALES_SERVICE_DATABASE}?authSource=admin

  mongodb_auth_service:
    image: mongo:latest
    container_name: mongodb_auth_service
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_AUTH_SERVICE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_AUTH_SERVICE_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_AUTH_SERVICE_DATABASE}
    ports:
      - "${MONGODB_AUTH_SERVICE_EXTERNAL_PORT}:${MONGODB_AUTH_SERVICE_INTERNAL_PORT}"
    volumes:
      - mongodb_auth_data:/data/db
    restart: unless-stopped

  mongodb_customer_service:
    image: mongo:latest
    container_name: mongodb_customer_service
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_CUSTOMER_SERVICE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_CUSTOMER_SERVICE_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_CUSTOMER_SERVICE_DATABASE}
    ports:
      - "${MONGODB_CUSTOMER_SERVICE_EXTERNAL_PORT}:${MONGODB_CUSTOMER_SERVICE_INTERNAL_PORT}"
    volumes:
      - mongodb_customer_data:/data/db
    restart: unless-stopped

  mongodb_sales_service:
    image: mongo:latest
    container_name: mongodb_sales_service
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_SALES_SERVICE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_SALES_SERVICE_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_SALES_SERVICE_DATABASE}
    ports:
      - "${MONGODB_SALES_SERVICE_EXTERNAL_PORT}:${MONGODB_SALES_SERVICE_INTERNAL_PORT}"
    volumes:
      - mongodb_sales_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_auth_data:
  mongodb_customer_data:
  mongodb_sales_data:
